name: yaroom
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  auth0: ^2.0.1
  badges: ^2.0.1
  bloc: ^7.0.0
  bottom_navy_bar: ^6.0.0
  bubble: ^1.2.1
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.2
  emoji_picker_flutter:
    git:
      url: https://github.com/Fintasys/emoji_picker_flutter
  equatable: ^2.0.3
  faker: ^2.0.0
  file_picker: ^3.0.3
  firebase_core: ^1.4.0
  firebase_messaging: ^10.0.4
  flutter:
    sdk: flutter
  flutter_appauth: ^1.1.0
  flutter_bloc: ^7.0.1
  flutter_image_compress: ^1.1.0
  flutter_local_notifications: ^9.0.0
  flutter_secure_storage: ^4.2.0
  flutter_spinkit: ^5.1.0
  http: ^0.13.3
  hydrated_bloc: ^7.0.1
  image_cropper: ^1.4.1
  moor: ^4.4.0
  path: ^1.8.0
  path_provider: ^2.0.2
  permission_handler: ^8.1.4+2
  provider: ^5.0.0
  sqlite3_flutter_libs: ^0.5.0
  url_launcher: ^6.0.9

dev_dependencies:
  build_runner: ^2.0.5
  flutter_launcher_icons: "^0.9.0"
  flutter_test:
    sdk: flutter
  moor_generator: ^4.4.0

flutter_icons:
  image_path: "assets/yaroom_only_logo_200x200.png"
  android: true

flutter:
  fonts:
    - family: NotoColorEmoji
      fonts:
        - asset: fonts/NotoColorEmoji_WindowsCompatible.ttf
  uses-material-design: true

  assets:
    - assets/
