version: '3'
services:

  yaroom-rabbitmq:
    container_name: yaroom-rabbitmq
    image: rabbitmq:3.8.19-management
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    volumes:
      - type: bind
        source: ~/containerVolumes/rabbitmq
        target: /var/lib/rabbitmq/mnesia/
    networks:
      - yaroom-testing

  yaroom-redis:
    container_name: yaroom-redis
    image: redis:6.2.4
    ports:
      - "6379:6379"
    restart: always
    networks:
      - yaroom-testing

  yaroom-mongodb:
    container_name: yaroom-mongodb
    image: mongo:5.0.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /data/db
    volumes:
      - type: bind
        source: ~/containerVolumes/mongodb
        target: /data/db
    ports:
      - "27017:27017"
    networks:
      - yaroom-testing

networks:
  yaroom-testing: