version: '3'
services:


  nats-js:
    container_name: yaroom-nats-js
    image: nats:2.6.2
    ports:
      - "4222:4222"
      - "8222:8222"
    command: -js
    networks:
      - yaroom-testing

  minio:
    container_name: yaroom-minio
    image: minio/minio:RELEASE.2021-07-15T22-27-34Z
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - type: bind
        source: ~/containerVolumes/minio
        target: /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - yaroom-testing

    
  els_node:
    container_name: yaroom-elassandra
    image: "docker.io/strapdata/elassandra:6.8.4.3"
    environment:
      - "JVM_OPTS=-Dcassandra.custom_query_handler_class=org.elassandra.index.ElasticQueryHandler"
      - "MAX_HEAP_SIZE=1200m"
      - "HEAP_NEWSIZE=300m"
      - "CASSANDRA_CGROUP_MEMORY_LIMIT=true"
      - "DEBUG=true"
    volumes:
      - type: bind
        source: ~/containerVolumes/elassandra
        target: /var/lib/cassandra
      - type: bind
        source: ~/containerVolumes/logs/elassandra
        target: /var/log/cassandra
    ports:
      - "9042:9042"
      - "9200:9200"
    networks:
      - yaroom-testing

  kibana:
    container_name: yaroom-kibana
    image: docker.elastic.co/kibana/kibana-oss:6.8.4
    environment:
      - "ELASTICSEARCH_URL=http://els_node:9200"
    ports:
      - "5601:5601"
    networks:
      - yaroom-testing

networks:
  yaroom-testing:
